name: Aviso BBB - 15 Minutos

on:
  schedule:
    # Roda às 01:44 UTC (22:44 de Brasília)
    - cron: '44 1 * * *'

jobs:
  enviar-aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": " sofá! Faltam só 15 minutos!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
