name: Manual - Aviso 15 Minutos

on:
  workflow_dispatch:

jobs:
  enviar-aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🛋️ **Todo mundo pro sofá!** Faltam só 15 minutos!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
