name: Manual - Aviso Começou

on:
  workflow_dispatch:

jobs:
  enviar-aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "📺 **COMEÇOU! CHAMA A ORCA E CORRE PRA TV QUE O BBB TÁ NO AR!**"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
