name: Aviso BBB - 2 Minutos

on:
  schedule:
    # Roda às 01:57 UTC (22:57 de Brasília)
    - cron: '57 1 * * *'

jobs:
  enviar-aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🔥🔥🔥 **TÁ CHEGANDO!** 2 minutinhos!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
