name: Manual - Aviso 5 Minutos

on:
  workflow_dispatch:

jobs:
  enviar-aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚨 **É QUASE HORA!** 5 minutos pra começar o fogo no parquinho!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
