name: Aviso BBB - 1 Hora Antes

on:
  schedule:
    # Roda às 00:59 UTC (21:59 de Brasília)
    - cron: '59 0 * * *'

jobs:
  enviar-aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "📢 **ESQUENTA BBB!** Falta 1 hora para começar! Já vai se preparando!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
