name: Manual - Aviso 10 Minutos

on:
  workflow_dispatch:

jobs:
  enviar-aviso:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "👀 **Atenção!** O BBB vai começar em 10 minutos!"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
